//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apphr.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apphr.Resources.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser una Bodega válida..
        /// </summary>
        public static string Bodega_NotExist {
            get {
                return ResourceManager.GetString("Bodega_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser un Departamento / Servicio válido..
        /// </summary>
        public static string Destino_NotExist {
            get {
                return ResourceManager.GetString("Destino_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser un documento de referencia válido..
        /// </summary>
        public static string DocumentRef_NotValid {
            get {
                return ResourceManager.GetString("DocumentRef_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un problema, intentente nuevamente, si el problema persiste, comuniquese con el adminstrador del sistema..
        /// </summary>
        public static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos datos no estan correctos, intente nuevamente o comuniquese con el administrador..
        /// </summary>
        public static string failure_model_invalid {
            get {
                return ResourceManager.GetString("failure_model_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser un Material válido..
        /// </summary>
        public static string Material_NotExist {
            get {
                return ResourceManager.GetString("Material_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser una Orden de Compra válida..
        /// </summary>
        public static string OrdenCompra_NotExist {
            get {
                return ResourceManager.GetString("OrdenCompra_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser un RM Válido..
        /// </summary>
        public static string PacienteRM_NotExist {
            get {
                return ResourceManager.GetString("PacienteRM_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privielegios insuficientes para realizar esta acción..
        /// </summary>
        public static string privileges_none {
            get {
                return ResourceManager.GetString("privileges_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ser un Nit de Proveedor válido..
        /// </summary>
        public static string Proveedor_NotExist {
            get {
                return ResourceManager.GetString("Proveedor_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado con éxito..
        /// </summary>
        public static string success_create {
            get {
                return ResourceManager.GetString("success_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado con éxito..
        /// </summary>
        public static string success_delete {
            get {
                return ResourceManager.GetString("success_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editado con éxito..
        /// </summary>
        public static string success_edit {
            get {
                return ResourceManager.GetString("success_edit", resourceCulture);
            }
        }
    }
}
