// <auto-generated />
namespace Apphr.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inventario22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inventario22));
        
        string IMigrationMetadata.Id
        {
            get { return "202210031606217_Inventario-22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
