// <auto-generated />
namespace Apphr.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inventario44 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inventario44));
        
        string IMigrationMetadata.Id
        {
            get { return "202302071449016_Inventario-44"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
